POST http://localhost:4002/products
content-Type: application/json
// CADASTRAR PRODUTO

{
    "name": "Borracha",
    "price": 1.50
}

###
// MOSTRAR PRODUTOS CADASTRADOS
GET http://localhost:4002/products

###
// BUSCAR PRODUTO COM A ID
GET http://localhost:4002/products/

###
// ATUALIZAR PRODUTO COM A ID
PUT http://localhost:4002/products/
content-Type: application/json

{
    "name": "Caderno 96 folhas",
    "price": 12
}

###
// DELETAR PRODUTO COM A ID
DELETE http://localhost:4002/products/