POST http://localhost:4002/products
content-Type: application/json
// CADASTRAR PRODUTO

{
    "name": "Borracha",
    "price": 1.50
}

###
// MOSTRAR PRODUTOS CADASTRADOS
GET http://localhost:4002/products

###
// BUSCAR PRODUTO COM A ID
GET http://localhost:4002/products/

###
// ATUALIZAR PRODUTO
PUT http://localhost:4002/products/e5bbcaf7-172c-40e1-a8a0-e32db7152766 
content-Type: application/json

{
    "name": "Caderno 96 folhas",
    "price": 12
}


###
// DELETAR PRODUTO
DELETE http://localhost:4002/products/ab153f56-da6a-4141-a847-948edba7db4e