POST http://localhost:4002/products
content-Type: application/json

{
    "name": "Caneta Azul",
    "price": 3.50
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/1707a018-cc7d-4351-97a5-388a23f5c0d8

